events {
    # Jeder Worker kann bis zu 1024 Verbindungen gleichzeitig offen halten
    worker_connections 1024; 
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        server_name $hostname;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~* \.(?:css|js|mjs|woff2|woff|ttf|otf)$ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000, immutable";
        }
    }
}